#' @importFrom matrixStats rowProds
NULL


#' Probability to detect one individual
#'
#' @description
#' A function that calculates the probability of detecting at least one
#' individual at a given time for a given trap configuration.
#'
#' @details
#' This function requires a simulation from `sim_spread()` and a data frame of
#' locations for the traps.  It returns the probability of detecting at least
#' one individual from the population in the region.
#'
#' @inherit run_surv
#' @param sim a simulation generated by `sim_spread()`.
#' @param surv_locs a data frame containing the locations of the traps.
#' @param use_manouk_error logical. If `TRUE` the mean probability of
#'   non-detected individuals is used in the detection probability.
#' @param run_surveil logical. If `TRUE`, returns surveillance of individuals.
#'
#' @return
#' If `run_surveil=FALSE`, only `p_cum_out` is returned.  Else, the following is
#' returned:
#' \item{`p_cum_out`}{The probability of detecting at least one individual.}
#' \item{`surv_res`}{A list showing the positive traps for each individual.}
#' \item{`surv_pts`}{A data frame containing the locations of the traps.}
#' \item{`sdm`}{A SpatRaster containing the sdm of the simulation.}
#'
#' @importFrom fields rdist
#' @importFrom stats rbinom
#' @export
p_detect_one <- function(sim = NULL, surv_locs = NULL,
                         g0 = 1.0, lam = 1/10, sig = 1,
                         det_func = "Manouk", use_manouk_error = FALSE,
                         run_surveil = FALSE) {

  if (is.null(sim)) {
    stop("Error: Please supply pest simulation")
  }
  if (is.null(surv_locs)) {
    stop("Error: Please supply surveillance locations")
  }

  dat         <- sim[["dat"]]
  p_non_detect <- numeric(length(dat))
  surv_mat    <- as.matrix(surv_locs[, c("x", "y")])

  if (run_surveil) {
    surv_out <- vector("list", length(dat))
  }

  for (i in seq_along(dat)) {

    pest_locs <- as.matrix(dat[[i]][, c("x", "y")])

    pwd_pest_surv <- rdist(pest_locs, surv_mat)

    if (det_func == "HalfNorm") {
      pwd_probs <- p_halfnorm(d = pwd_pest_surv, g0 = g0, sig = sig)
    } else {
      pwd_probs <- p_manouk(d = pwd_pest_surv, g0 = g0, lam = lam)
    }

    pwd_probs_bar       <- 1 - pwd_probs
    p_indiv_non_detect  <- rowProds(pwd_probs_bar)
    p_non_detect[i]     <- prod(p_indiv_non_detect)

    if (use_manouk_error) {
      p_non_detect[i] <- mean(p_indiv_non_detect)
    }

    if (run_surveil) {
      # Vectorized Bernoulli draws
      surv_detect  <- matrix(rbinom(length(pwd_probs), 1L, pwd_probs),
                              nrow = nrow(pwd_probs))
      trap_detect  <- colSums(surv_detect)
      pos_trap_nos <- surv_locs[which(trap_detect > 0), ]
      surv_out[[i]] <- list(pos_trap_nos = pos_trap_nos, dat = dat[[i]])
    }
  }

  p_cum_out <- 1 - sapply(seq_along(p_non_detect),
                           function(i) prod(p_non_detect[seq_len(i)]))

  if (run_surveil) {
    return(list(
      p_cum_out = p_cum_out,
      surv_res  = surv_out,
      surv_pts  = surv_locs,
      sdm       = sim$sdm
    ))
  } else {
    return(p_cum_out)
  }
}
