
#' Half normal detection function
#'
#' @description
#' Calculates the half-normal detection function
#'
#' @details
#' Function that returns detection based on half-normal detection function
#'
#' @param d
#' @param g0
#' @param sig
#'
#' @export
p_halfnorm <- function(d, g0=0.7, sig=1) {
  # Args:
  # d - distance from device
  # g0 - P(Detect | d=0)
  # sig - standard deviation of detection
  g0*exp(-d^2/(2*sig^2))
}

#' Manouk's detection function
#'
#' @description
#' Calculates Manouk's detection function
#'
#' @details
#' Function that returns detection based on Manouk's detection function
#'
#' @param d
#' @param g0
#' @param lam
#'
#' @export
p_manouk <- function(d, g0=1.0,lam=1/10) {
  # Args:
  #	d - distance from device
  #	g0 - P(Detect | d=0)
  2*g0/(exp(lam*d)+exp(-lam*d))
}

#' Run Surveillance
#'
#' @description
#' Helper function to run surveillance.
#'
#' @details
#' Function that returns
#'
#' @param sim a simulation object generated by `sim_spread()`
#' @param surv_pts a data frame of surveillance points
#' @param g0,sig,lam parameters to pass to detection functions based on
#'   `det_func` argument.
#' @param det_func a string indicating which detection function to use.  Either
#'   "Manouk" or "HalfNorm".  "Manouk" calls the function `p_manouk()`.  "HalfNorm"
#'   calls `p_halfnorm()`.  See help from those functions for details.
#'
#' @export
run_surv <- function(sim=NULL, surv_pts=NULL, g0=0.5,
                     sig=1, lam=1/10, det_func="Manouk") {
  # Args:
  ###	sim -- sim objected generated by sim_spread()
  ###	surv_pts -- data.frame of survey points
  ### g0 -- used for p_halfnorm() and p_manouk()
  ###	lam -- detectability for p_mankou()
  ###	sig -- variance for p_halfnorm()
  ###	det_func -- detection function to use, either "Manouk" or "HalfNorm"
  # Returns:
  ###	surv_res --
  ### surv_pts --
  ### sdm --

  # List to record surveillance data
  surv_out <- list()
  dat <- sim[["dat"]]

  # For all time steps (slow loop, use lapply())
  for (i in 1:length(dat)) {
    # Grab point data
    sim_pts <- dat[[i]][,c('x','y')]

    # Pairwise distances (pwd) between critters and surveillance devices
    pwd_spp_surv <- rdist(sim_pts,surv_pts[,c('x','y')])

    # Calculate probabilities of detection for all pairwise distances
    if(det_func=="HalfNorm") {
      pwd_probs <- apply(pwd_spp_surv, c(1,2),
                         function(x) p_halfnorm(d=x, g0=g0, sig=sig))
    }
    if(det_func=="Manouk") {
      pwd_probs <- apply(pwd_spp_surv, c(1,2),
                         function(x) p_manouk(d=x, g0=g0, lam=lam))
    }

    # Sample detections randomly (ignoring competition for critters)
    surv_detect <- apply(pwd_probs,c(1,2), function(x) rbinom(1,1,x))

    # Sum detections by trap
    trap_detect <- apply(surv_detect,2,sum)

    # Which traps caught something
    pos_trap_nos <- surv_pts[which(trap_detect>0),]

    # Save
    surv_out[[i]] <- list(pos_trap_nos=pos_trap_nos,dat=dat[[i]])
  }
  return(
    list(surv_res=surv_out,
         surv_pts=surv_pts,
         sdm=sim$sdm
    ))
}
